# Generated by Django 4.2.6 on 2023-10-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointer', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
    ]
