# Generated by Django 4.2.6 on 2023-10-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointer', '0004_login_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='loginmodel',
        ),
    ]
