# Generated by Django 4.2.6 on 2023-10-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointer', '0005_rename_login_loginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
